services:
  trainerdb:
    container_name: trainerdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - trainermongo_data:/data/db


  clientdb:
    container_name: clientdb
    restart: always
    ports:
      - "27019:27017"
    volumes: 
      - clientmongo_data:/data/db

  reviewdb:
    container_name: reviewdb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - reviewmongo_data:/data/db
 
  paymentdb:
    container_name: paymentdb
    restart: always
    ports:
      - "27020:27017"
    volumes:
      - paymentmongo_data:/data/db
  
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  
  mssql:
    container_name: mssql
    environment:
      - SA_PASSWORD=MATF12345678rs2
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql/data
      - mssql_volume:/var/opt/sqlserver/
  
  
  consul:
    container_name: consul
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"
    volumes:
      - consul_data:/consul/data
      
  
  gatewayservice.api:
    container_name: gatewayservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8005:8080"    
  
  trainerservice.api:
    container_name: trainerservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://trainerdb:27017"
      - "GrpcSettings:ReviewUrl=http://reviewservice.grpc:8080"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672" 
    ports:
      - "8000:8080"

  clientservice.api:
    container_name: clientservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://clientdb:27017"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"  
    ports:
      - "8100:8080"

  identityserver:
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:IdentityConnectionString=Server=mssql;Database=IdentityDb;User Id=sa;Password=MATF12345678rs2;TrustServerCertificate=True;Encrypt=False;"
    ports:
      - "4000:8080"

  reviewservice.api:
    container_name: reviewservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://reviewdb:27017"
    ports:
      - "8001:8080"

  reviewservice.grpc:
    container_name: reviewservice.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://reviewdb:27017"
    ports:
      - "8002:8080"

  paymentservice.api:
    container_name: paymentservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://paymentdb:27017"
      - PAYPAL_CLIENT_ID="PayPalSettings:ClientId"
      - PAYPAL_CLIENT_SECRET="PayPalSettings:ClientSecret"
    ports:
      - "8003:8080"
