services:
  trainerdb:
    container_name: trainerdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - trainermongo_data:/data/db

  clientdb:
    container_name: clientdb
    restart: always
    ports:
      - "27019:27017"
    volumes: 
      - clientmongo_data:/data/db

  reviewdb:
    container_name: reviewdb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - reviewmongo_data:/data/db
 
  paymentdb:
    container_name: paymentdb
    restart: always
    ports:
      - "27020:27017"
    volumes:
      - paymentmongo_data:/data/db
        
  videotrainingdb:
    container_name: videotrainingdb
    restart: always
    ports:
      - "27030:27017"
    volumes:
      - videotrainingmongo_data:/data/db
  
  notificationdb:
    container_name: notificationdb
    restart: always
    ports:
      - "27021:27017"
    volumes:
      - notificationmongo_data:/data/db
  
  chatdb:
    container_name: chatdb
    restart: always
    ports:
      - "27022:27017"
    volumes:
      - chatmongo_data:/data/db
  
  reservationdb:
    container_name: reservationdb
    restart: always
    ports:
      - "27023:27017"
    volumes:
      - reservationmongo_data:/data/db
  
  analyticsdb:
    container_name: analyticsdb
    restart: always
    ports:
      - 27027:27017
    volumes:
      - analyticsmongo_data:/data/db
  
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  
  mssql:
    container_name: mssql
    environment:
      - SA_PASSWORD=MATF12345678rs2
      - ACCEPT_EULA=Y
    restart: always
    user: root
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql/
      - mssql_volume:/var/opt/sqlserver/
  
  consul:
    container_name: consul
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"
    volumes:
      - consul_data:/consul/data
      
  
  gatewayservice.api:
    container_name: gatewayservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8005:8080"    
  
  trainerservice.api:
    container_name: trainerservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://trainerdb:27017"
      - "GrpcSettings:ReviewUrl=http://host.docker.internal:8002"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672" 
    ports:
      - "8000:8080"
  
  trainerservice.grpc:
    container_name: trainerservice.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://trainerdb:27017"
    ports:
      - "8102:8080"

  clientservice.api:
    container_name: clientservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://clientdb:27017"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8100:8080"
        
  clientservice.grpc:
    container_name: clientservice.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://clientdb:27017"
    ports:
      - "8101:8080"

  identityserver:
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:IdentityConnectionString=Server=mssql;Database=IdentityDb;User Id=sa;Password=MATF12345678rs2;TrustServerCertificate=True;Encrypt=False;"
    ports:
      - "4000:8080"

  reviewservice.api:
    container_name: reviewservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://reviewdb:27017"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8001:8080"

  reviewservice.grpc:
    container_name: reviewservice.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://reviewdb:27017"
    ports:
      - "8002:8080"

  paymentservice.api:
    container_name: paymentservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://paymentdb:27017"
    env_file:
      - ./Services/PaymentService/PaymentService.API/.env
    ports:
      - "8003:8080"
  
  notificationservice.api:
    container_name: notificationservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://notificationdb:27017"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "EmailSettings:FromEmail=fitplusplus.rs2@gmail.com"
      - "EmailSettings:SmtpHost=smtp.gmail.com"
      - "EmailSettings:SmtpPort=587"
      - "EmailSettings:Username=fitplusplus.rs2@gmail.com"
      - "EmailSettings:EnableSsl=false"
      - "GrpcSettings:ClientUrl=http://host.docker.internal:8101"
      - "GrpcSettings:TrainerUrl=http://host.docker.internal:8102"
    env_file:
      - ./Services/NotificationService/NotificationService.API/.env
    ports:
      - "8004:8080"
    
  analyticsservice.api:
    container_name: analyticsservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://analyticsdb:27017"
      - "GrpcSettings:ReviewUrl=http://reviewservice.grpc:8080"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8018:8080"

  chatservice.api:
    container_name: chatService.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "MongoDB:ConnectionString=mongodb://chatdb:27017"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8082:8080"
        
  reservationservice.api:
    container_name: reservationservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://reservationdb:27017"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8103:8080"

  videotrainingservice.api:
    container_name: videotrainingservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSetting:ConnectionString=mongodb://videotrainingdb:27017"
    ports:
      - "8007:8080"