name: Prevent .env files in PRs

on:
  pull_request:
    branches:
      - main

jobs:
  check-env-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Search for .env files
        run: |
          if git diff --name-only origin/main...HEAD | grep -E '(^|/)\.env'; then
            echo "❌ PR contain .env file, merge is forbiden."
            exit 1
          else
            echo "✅ There are no .env files in this PR-u."
          fi
